#!/usr/bin/with-contenv zsh

ssh-keygen -A
echo -e "[init-ssh]\tGenerated server keys."


sed -i 's/AuthorizedKeysFile.*/AuthorizedKeysFile \/config\/.ssh\/authorized_keys/' /etc/ssh/sshd_config 
sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config 
sed -i 's/#Port 22/Port 22/g' /etc/ssh/sshd_config 
sed -i 's/#PidFile.*/PidFile \/config\/sshd.pid/g' /etc/ssh/sshd_config 
sed -i "s/#ListenAddress 0.0.0.0/ListenAddress ${SSH_LISTEN:-0.0.0.0}/g" /etc/ssh/sshd_config 
sed -i 's/#HostKey \/etc\/ssh\/ssh_host_rsa_key/HostKey \/etc\/ssh\/ssh_host_rsa_key/g' /etc/ssh/sshd_config 
sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/g' /etc/ssh/sshd_config 

echo -e "[init-ssh]\tSet up /etc/ssh/sshd_config."


chown -R git:users /etc/ssh/
echo -e "[init-ssh]\tSet permissions of /etc/ssh to git:users."